### ISSUE TITLE
Unable to load ka-table

### ISSUE THREAD

**Issue by pchaganti** [komarovalexander/ka-table#317]
I am working inside a VScode devcontainer. Getting an error when loading ka-table. Any idea why it cant find these files? Using version 7.14.0

```
1:52:57 PM [vite] error while updating dependencies:
Error: Build failed with 92 errors:
node_modules/ka-table/Components/CellComponent/CellComponent.js:42:31: ERROR: Could not resolve "../../Utils/ComponentUtils"
node_modules/ka-table/Components/CellEditor/CellEditor.js:43:26: ERROR: Could not resolve "../../Utils/CellUtils"
node_modules/ka-table/Components/CellEditor/CellEditor.js:44:31: ERROR: Could not resolve "../../Utils/ComponentUtils"
node_modules/ka-table/Components/CellEditorBoolean/CellEditorBoolean.js:20:28: ERROR: Could not resolve "../../Utils/CommonUtils"
node_modules/ka-table/Components/CellEditorBoolean/CellEditorBoolean.js:21:31: ERROR: Could not resolve "../../Utils/ComponentUtils"
...
    at failureErrorWithLog (/workspaces/myworkspace/frontend/node_modules/vite/node_modules/esbuild/lib/main.js:1636:15)
    at /workspaces/myworkspace/frontend/node_modules/vite/node_modules/esbuild/lib/main.js:1048:25
    at runOnEndCallbacks (/workspaces/myworkspace/frontend/node_modules/vite/node_modules/esbuild/lib/main.js:1471:45)
    at buildResponseToResult (/workspaces/myworkspace/frontend/node_modules/vite/node_modules/esbuild/lib/main.js:1046:7)
    at /workspaces/myworkspace/frontend/node_modules/vite/node_modules/esbuild/lib/main.js:1058:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (/workspaces/myworkspace/frontend/node_modules/vite/node_modules/esbuild/lib/main.js:1057:54)
    at handleRequest (/workspaces/myworkspace/frontend/node_modules/vite/node_modules/esbuild/lib/main.js:723:19)
    at handleIncomingPacket (/workspaces/myworkspace/frontend/node_modules/vite/node_modules/esbuild/lib/main.js:745:7)
    at Socket.readFromStdout (/workspaces/myworkspace/frontend/node_modules/vite/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by pchaganti** [comment]
This is an issue with vite. Switched to webpack. Works fine now.

thanks!
